/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check if the API server is healthy and responding.
         *
         *     Returns:
         *         HealthResponse: A status indicating the server is operational.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Products
         * @description List products, optionally including inactive ones.
         *
         *     Args:
         *         include_inactive: When True, inactive products are included.
         *             Mirrors the CLI ``--all`` flag. Defaults to False.
         *         context: Runtime context injected via dependency.
         *
         *     Returns:
         *         ProductListResponse containing the matching product records.
         */
        get: operations["list_products_products_get"];
        put?: never;
        /**
         * Create Product
         * @description Create a new product.
         *
         *     Args:
         *         request: Product creation payload.
         *         context: Runtime context injected via dependency.
         *
         *     Returns:
         *         StandardResponse containing the created product data.
         *
         *     Raises:
         *         HTTPException: 409 if product already exists, 400 for validation errors.
         */
        post: operations["create_product_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate Product
         * @description Deactivate an existing product.
         *
         *     Args:
         *         product_id: The ID of the product to deactivate.
         *         context: Runtime context injected via dependency.
         *
         *     Returns:
         *         StandardResponse containing the updated product data.
         *
         *     Raises:
         *         HTTPException: 404 if product not found.
         */
        post: operations["deactivate_product_products__product_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salesmen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Salesmen
         * @description List salesmen, optionally including inactive ones.
         *
         *     Args:
         *         include_inactive: When True, inactive salesmen are included.
         *             Mirrors the CLI ``--all`` flag. Defaults to False.
         *         context: Runtime context injected via dependency.
         *
         *     Returns:
         *         SalesmanListResponse containing the matching salesman records.
         */
        get: operations["list_salesmen_salesmen_get"];
        put?: never;
        /**
         * Create Salesman
         * @description Create a new salesman.
         *
         *     Args:
         *         request: Salesman creation payload.
         *         context: Runtime context injected via dependency.
         *
         *     Returns:
         *         StandardResponse containing the created salesman data.
         *
         *     Raises:
         *         HTTPException: 409 if salesman already exists, 400 for validation errors.
         */
        post: operations["create_salesman_salesmen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salesmen/{salesman_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate Salesman
         * @description Deactivate an existing salesman.
         *
         *     Args:
         *         salesman_id: The ID of the salesman to deactivate.
         *         context: Runtime context injected via dependency.
         *
         *     Returns:
         *         StandardResponse containing the updated salesman data.
         *
         *     Raises:
         *         HTTPException: 404 if salesman not found.
         */
        post: operations["deactivate_salesman_salesmen__salesman_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/sale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Sale
         * @description Record a sale transaction.
         *
         *     Args:
         *         request: Sale transaction payload.
         *         context: Runtime context injected via dependency.
         *
         *     Returns:
         *         StandardResponse containing the created transaction data.
         *
         *     Raises:
         *         HTTPException: 409 for business rule violations, 404 for missing references.
         */
        post: operations["record_sale_transactions_sale_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/restock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Restock
         * @description Record a restock transaction.
         *
         *     Args:
         *         request: Restock transaction payload.
         *         context: Runtime context injected via dependency.
         *
         *     Returns:
         *         StandardResponse containing the created transaction data.
         *
         *     Raises:
         *         HTTPException: 409 for business rule violations, 404 for missing references.
         */
        post: operations["record_restock_transactions_restock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/write-off": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Write Off
         * @description Record a write-off transaction.
         *
         *     Args:
         *         request: Write-off transaction payload.
         *         context: Runtime context injected via dependency.
         *
         *     Returns:
         *         StandardResponse containing the created transaction data.
         *
         *     Raises:
         *         HTTPException: 409 for business rule violations, 404 for missing references.
         */
        post: operations["record_write_off_transactions_write_off_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Void
         * @description Void an existing transaction.
         *
         *     Args:
         *         request: Void transaction payload.
         *         context: Runtime context injected via dependency.
         *
         *     Returns:
         *         StandardResponse containing the created void transaction data.
         *
         *     Raises:
         *         HTTPException: 409 for business rule violations, 404 for missing references.
         */
        post: operations["record_void_transactions_void_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/pay-debt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Pay Debt
         * @description Record a credit payment for an outstanding sale.
         *
         *     Args:
         *         request: Credit payment payload.
         *         context: Runtime context injected via dependency.
         *
         *     Returns:
         *         StandardResponse containing the created transaction data.
         *
         *     Raises:
         *         HTTPException: 409 for business rule violations, 404 for missing references.
         */
        post: operations["record_pay_debt_transactions_pay_debt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock Report
         * @description Get current stock levels for all products.
         *
         *     Args:
         *         context: Runtime context injected via dependency.
         *
         *     Returns:
         *         StockReportResponse containing inventory levels per product.
         */
        get: operations["get_stock_report_reports_stock_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/profit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profit Report
         * @description Get profit summary with revenue and cost totals.
         *
         *     Args:
         *         context: Runtime context injected via dependency.
         *
         *     Returns:
         *         ProfitReportResponse containing revenue, cost, and profit totals.
         */
        get: operations["get_profit_report_reports_profit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/debts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Debts Report
         * @description Get outstanding credit balances.
         *
         *     Args:
         *         context: Runtime context injected via dependency.
         *
         *     Returns:
         *         DebtsReportResponse containing outstanding balances and total.
         */
        get: operations["get_debts_report_reports_debts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Log Report
         * @description Get the full transaction log.
         *
         *     Args:
         *         context: Runtime context injected via dependency.
         *
         *     Returns:
         *         LogReportResponse containing all transactions.
         */
        get: operations["get_log_report_reports_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DebtItem
         * @description Single outstanding debt entry.
         */
        DebtItem: {
            /** Transaction Id */
            transaction_id: string;
            /** Timestamp Iso */
            timestamp_iso: string;
            /** Product Id */
            product_id: string | null;
            /** Salesman Id */
            salesman_id: string | null;
            /** Quantity */
            quantity: string;
            /** Expected Amount */
            expected_amount: string;
            /** Amount Paid */
            amount_paid: string;
            /** Balance */
            balance: string;
        };
        /**
         * DebtsReportResponse
         * @description Response for the debts report endpoint.
         */
        DebtsReportResponse: {
            /** Balances */
            balances: components["schemas"]["DebtItem"][];
            /** Total Outstanding */
            total_outstanding: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response model for the health check endpoint.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /**
         * LogReportResponse
         * @description Response for the transaction log report endpoint.
         */
        LogReportResponse: {
            /** Transactions */
            transactions: components["schemas"]["TransactionResponse"][];
        };
        /**
         * PayDebtRequest
         * @description Request payload for recording a credit payment.
         */
        PayDebtRequest: {
            /** Linked Transaction Id */
            linked_transaction_id: string;
            /** Salesman Id */
            salesman_id: string;
            /** Total Revenue */
            total_revenue: number | string;
            payment_type: components["schemas"]["PaymentType"];
            /** Notes */
            notes?: string | null;
        };
        /**
         * PaymentType
         * @description Enumerate supported payment mechanisms for sales.
         * @enum {string}
         */
        PaymentType: "Cash" | "OnCredit" | "PIX" | "Other";
        /**
         * ProductCreateRequest
         * @description Request payload for creating a new product.
         */
        ProductCreateRequest: {
            /** Product Id */
            product_id: string;
            /** Product Name */
            product_name: string;
            /** Sell Price */
            sell_price: number | string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /**
         * ProductListResponse
         * @description Response for listing products.
         */
        ProductListResponse: {
            /** Items */
            items: components["schemas"]["ProductResponse"][];
        };
        /**
         * ProductResponse
         * @description Response representation of a product record.
         */
        ProductResponse: {
            /** Product Id */
            product_id: string;
            /** Product Name */
            product_name: string;
            /** Sell Price */
            sell_price: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * ProfitReportResponse
         * @description Response for the profit report endpoint.
         */
        ProfitReportResponse: {
            /** Total Revenue */
            total_revenue: string;
            /** Total Cost */
            total_cost: string;
            /** Profit */
            profit: string;
        };
        /**
         * RestockRequest
         * @description Request payload for recording a restock transaction.
         */
        RestockRequest: {
            /** Product Id */
            product_id: string;
            /** Salesman Id */
            salesman_id: string;
            /** Quantity */
            quantity: number | string;
            /** Total Cost */
            total_cost: number | string;
            /** Notes */
            notes?: string | null;
        };
        /**
         * SaleRequest
         * @description Request payload for recording a sale transaction.
         */
        SaleRequest: {
            /** Product Id */
            product_id: string;
            /** Salesman Id */
            salesman_id: string;
            /** Quantity */
            quantity: number | string;
            /** Total Revenue */
            total_revenue: number | string;
            payment_type: components["schemas"]["PaymentType"];
            /** Notes */
            notes?: string | null;
        };
        /**
         * SalesmanCreateRequest
         * @description Request payload for creating a new salesman.
         */
        SalesmanCreateRequest: {
            /** Salesman Id */
            salesman_id: string;
            /** Salesman Name */
            salesman_name: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /**
         * SalesmanListResponse
         * @description Response for listing salesmen.
         */
        SalesmanListResponse: {
            /** Items */
            items: components["schemas"]["SalesmanResponse"][];
        };
        /**
         * SalesmanResponse
         * @description Response representation of a salesman record.
         */
        SalesmanResponse: {
            /** Salesman Id */
            salesman_id: string;
            /** Salesman Name */
            salesman_name: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * StandardResponse
         * @description Standard wrapper for mutation endpoint responses.
         *
         *     The `data` field uses `Any` to allow flexibility across different entity
         *     types (Product, Salesman, Transaction). Individual endpoints ensure type
         *     safety by constructing specific response DTOs before wrapping them.
         */
        StandardResponse: {
            /** Detail */
            detail: string;
            /** Data */
            data?: unknown | null;
        };
        /**
         * StockItem
         * @description Single item in the stock report.
         */
        StockItem: {
            /** Product Id */
            product_id: string;
            /** Quantity */
            quantity: string;
        };
        /**
         * StockReportResponse
         * @description Response for the stock report endpoint.
         */
        StockReportResponse: {
            /** Items */
            items: components["schemas"]["StockItem"][];
        };
        /**
         * TransactionResponse
         * @description Response representation of a transaction record.
         */
        TransactionResponse: {
            /** Transaction Id */
            transaction_id: string;
            /** Timestamp Iso */
            timestamp_iso: string;
            /** Transaction Type */
            transaction_type: string;
            /** Product Id */
            product_id: string | null;
            /** Salesman Id */
            salesman_id: string | null;
            /** Payment Type */
            payment_type: string | null;
            /** Quantity Change */
            quantity_change: string;
            /** Total Revenue */
            total_revenue: string;
            /** Total Cost */
            total_cost: string;
            /** Linked Transaction Id */
            linked_transaction_id: string | null;
            /** Notes */
            notes: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VoidRequest
         * @description Request payload for voiding an existing transaction.
         */
        VoidRequest: {
            /** Linked Transaction Id */
            linked_transaction_id: string;
            /** Notes */
            notes?: string | null;
        };
        /**
         * WriteOffRequest
         * @description Request payload for recording a write-off transaction.
         */
        WriteOffRequest: {
            /** Product Id */
            product_id: string;
            /** Salesman Id */
            salesman_id: string;
            /** Quantity */
            quantity: number | string;
            /** Notes */
            notes?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_products_products_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_product_products__product_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_salesmen_salesmen_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesmanListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_salesman_salesmen_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalesmanCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_salesman_salesmen__salesman_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                salesman_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_sale_transactions_sale_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_restock_transactions_restock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_write_off_transactions_write_off_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteOffRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_void_transactions_void_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoidRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_pay_debt_transactions_pay_debt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayDebtRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_report_reports_stock_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockReportResponse"];
                };
            };
        };
    };
    get_profit_report_reports_profit_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfitReportResponse"];
                };
            };
        };
    };
    get_debts_report_reports_debts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtsReportResponse"];
                };
            };
        };
    };
    get_log_report_reports_log_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogReportResponse"];
                };
            };
        };
    };
}
